import { ImageSourcePropType } from "react-native";

type ImageTypes = {
  [key: string]: ImageSourcePropType;
};

const Images: ImageTypes = {
  logo: require("../assets/images/logo.png"),
  onBordingOne: require("../assets/images/onBordingOne.png"),
  onBording: require("../assets/images/onboarding.png"),
  onBordingTwo: require("../assets/images/onBordingTwo.png"),
  onBordingThree: require("../assets/images/onBordingThree.png"),
  facebook: require("../assets/images/facebooks.png"),
  google: require("../assets/images/googles.png"),
  apple: require("../assets/images/applepng.png"),
  livingRoom: require("../assets/images/Login.png"),
  bannerThree: require("../assets/images/bannerThree.jpg"),
  bannerFour: require("../assets/images/bannerFour.jpg"),
  based: require("../assets/images/baseOne.png"),
  banner: require("../assets/images/banner.jpg"),
  sofa: require("../assets/images/sofa.png"),
  BuddyChair: require("../assets/images/BuddyChiar.png"),
  wingBack: require("../assets/images/wingBack.png"),
  blueChair: require("../assets/images/blueChair.png"),
  woodChair: require("../assets/images/woodChair.png"),
  blueSofa: require("../assets/images/blueSofa.png"),
  user: require("../assets/images/user.png"),
  flowerPort: require("../assets/images/flowerPort.png"),
  chair: require("../assets/images/chair.png"),
  lamp: require("../assets/images/lamp.png"),
  blueLamp: require("../assets/images/blueLamp.png"),
  photoPort: require("../assets/images/photoPort.png"),
  masterCArd: require("../assets/images/mastercard.png"),
  visa: require("../assets/images/visa.png"),
  helppic: require("../assets/images/helppic.png"),
  cafeLight: require("../assets/images/cafeLight.png"),
  coupBoard: require("../assets/images/coupBoard.png"),
  dressingTable: require("../assets/images/dressingTable.png"),
  sofaChair: require("../assets/images/sofaChair.png"),
  swing: require("../assets/images/swing.png"),
  stool: require("../assets/images/stool.png"),
  metricChair: require("../assets/images/metricChiar.png"),
  cafelightBlack: require("../assets/images/cafelightBlack.png"),
  portTable: require("../assets/images/portTable.png"),
  Base: require("../assets/images/Base.png"),
  megaSale: require("../assets/images/megaSale.png"),
  userFull: require("../assets/images/userFull.png"),
  buddyChairFive: require("../assets/images/buddychairFive.png"),
  buddyChairFour: require("../assets/images/buddyChairFour.png"),
  buddyChairThree: require("../assets/images/buddyChairThree.png"),
  buddyChairSix: require("../assets/images/buddyChairSix.png"),
  bannerTwo: require("../assets/images/bannerTwo.jpg"),
  swingsTwo: require("../assets/images/swingsTwo.png"),
  bed: require("../assets/images/bed.png"),
  portLight: require("../assets/images/portLight.png"),
  blackChair: require("../assets/images/blackChair.png"),
  bookMark: require("../assets/images/bookMark.png"),
  cart: require("../assets/images/gif/cart.gif"),
  cartDark: require("../assets/images/gif/cartDark.gif"),
  notifiction: require("../assets/images/gif/notifiction.gif"),
  notifictionDark: require("../assets/images/gif/notificationDark.gif"),
  orderGif: require("../assets/images/gif/order.gif"),
  orderDarkGif: require("../assets/images/gif/orderDark.gif"),
  search: require("../assets/images/gif/search.gif"),
  searchDark: require("../assets/images/gif/searchDark.gif"),
  success: require("../assets/images/gif/success.gif"),
  wishlist: require("../assets/images/gif/wishlist.gif"),
  wishlistDark: require("../assets/images/gif/whishListDark.gif"),
  headerBg: require("../assets/images/headerbg.png"),
  yellowChair: require("../assets/images/yellowChair.png"),
  yellowChairTwo: require("../assets/images/yellowChairTwo.png"),
  voucher: require("../assets/images/voucher.png"),
  paymentDone: require("../assets/images/gif/paymentDone.gif"),
  paymentDoneDark: require("../assets/images/gif/paymentDoneDark.gif"),
  apay: require("../assets/images/apay.png"),
  paypal: require("../assets/images/paypal.png"),
  gpay: require("../assets/images/gpay.png"),
  cash: require("../assets/images/cash.png"),
  reviewOne: require("../assets/images/reviewOne.png"),
  reviewTwo: require("../assets/images/reviewTwo.png"),
  sideBookMark: require("../assets/images/sideBookMark.png"),
  productCircle: require("../assets/images/productCircle.png"),
  whiteCafeLight: require("../assets/images/whiteCafeLight.png"),
  darkApple: require("../assets/images/darkApple.png"),
  darkVisa: require("../assets/images/darkVisa.png"),
  voucherDark: require("../assets/images/voucherDark.png"),
};

export default Images;
